In [61]:
import numpy as np

Задание 1

In [62]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [63]:
a_mean = a.mean(axis=0, keepdims = True)
a_mean

array([[2. , 8.4]])

Задание 2

In [64]:
a_centered = a - a_mean
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [65]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp = a_centered_sp / (a.shape[0] - 1)
a_centered_sp

2.0

Задание 4

In [66]:
a_T = np.transpose(a)
a_T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [67]:
a_cov = np.cov(a_T)
a_cov[0, 1]

2.0